import type { Country } from './types';

export const countries: Country[] = [
  { name: 'France', code: 'FR', dialCode: '+33' },
  { name: 'Mauritanie', code: 'MR', dialCode: '+222' },
  { name: 'Afghanistan', code: 'AF', dialCode: '+93' },
  { name: 'Albanie', code: 'AL', dialCode: '+355' },
  { name: 'Algérie', code: 'DZ', dialCode: '+213' },
  { name: 'Andorre', code: 'AD', dialCode: '+376' },
  { name: 'Angola', code: 'AO', dialCode: '+244' },
  { name: 'Argentine', code: 'AR', dialCode: '+54' },
  { name: 'Arménie', code: 'AM', dialCode: '+374' },
  { name: 'Australie', code: 'AU', dialCode: '+61' },
  { name: 'Autriche', code: 'AT', dialCode: '+43' },
  { name: 'Azerbaïdjan', code: 'AZ', dialCode: '+994' },
  { name: 'Bahamas', code: 'BS', dialCode: '+1-242' },
  { name: 'Bahreïn', code: 'BH', dialCode: '+973' },
  { name: 'Bangladesh', code: 'BD', dialCode: '+880' },
  { name: 'Barbade', code: 'BB', dialCode: '+1-246' },
  { name: 'Biélorussie', code: 'BY', dialCode: '+375' },
  { name: 'Belgique', code: 'BE', dialCode: '+32' },
  { name: 'Bénin', code: 'BJ', dialCode: '+229' },
  { name: 'Bolivie', code: 'BO', dialCode: '+591' },
  { name: 'Brésil', code: 'BR', dialCode: '+55' },
  { name: 'Bulgarie', code: 'BG', dialCode: '+359' },
  { name: 'Burkina Faso', code: 'BF', dialCode: '+226' },
  { name: 'Cambodge', code: 'KH', dialCode: '+855' },
  { name: 'Cameroun', code: 'CM', dialCode: '+237' },
  { name: 'Canada', code: 'CA', dialCode: '+1' },
  { name: 'Chili', code: 'CL', dialCode: '+56' },
  { name: 'Chine', code: 'CN', dialCode: '+86' },
  { name: 'Colombie', code: 'CO', dialCode: '+57' },
  { name: 'Congo (RDC)', code: 'CD', dialCode: '+243' },
  { name: 'Costa Rica', code: 'CR', dialCode: '+506' },
  { name: 'Côte d\'Ivoire', code: 'CI', dialCode: '+225' },
  { name: 'Croatie', code: 'HR', dialCode: '+385' },
  { name: 'Cuba', code: 'CU', dialCode: '+53' },
  { name: 'Chypre', code: 'CY', dialCode: '+357' },
  { name: 'République tchèque', code: 'CZ', dialCode: '+420' },
  { name: 'Danemark', code: 'DK', dialCode: '+45' },
  { name: 'Égypte', code: 'EG', dialCode: '+20' },
  { name: 'Estonie', code: 'EE', dialCode: '+372' },
  { name: 'Finlande', code: 'FI', dialCode: '+358' },
  { name: 'Allemagne', code: 'DE', dialCode: '+49' },
  { name: 'Grèce', code: 'GR', dialCode: '+30' },
  { name: 'Hongrie', code: 'HU', dialCode: '+36' },
  { name: 'Islande', code: 'IS', dialCode: '+354' },
  { name: 'Inde', code: 'IN', dialCode: '+91' },
  { name: 'Indonésie', code: 'ID', dialCode: '+62' },
  { name: 'Iran', code: 'IR', dialCode: '+98' },
  { name: 'Irak', code: 'IQ', dialCode: '+964' },
  { name: 'Irlande', code: 'IE', dialCode: '+353' },
  { name: 'Israël', code: 'IL', dialCode: '+972' },
  { name: 'Italie', code: 'IT', dialCode: '+39' },
  { name: 'Japon', code: 'JP', dialCode: '+81' },
  { name: 'Jordanie', code: 'JO', dialCode: '+962' },
  { name: 'Kenya', code: 'KE', dialCode: '+254' },
  { name: 'Liban', code: 'LB', dialCode: '+961' },
  { name: 'Luxembourg', code: 'LU', dialCode: '+352' },
  { name: 'Malaisie', code: 'MY', dialCode: '+60' },
  { name: 'Mali', code: 'ML', dialCode: '+223' },
  { name: 'Maroc', code: 'MA', dialCode: '+212' },
  { name: 'Mexique', code: 'MX', dialCode: '+52' },
  { name: 'Pays-Bas', code: 'NL', dialCode: '+31' },
  { name: 'Nouvelle-Zélande', code: 'NZ', dialCode: '+64' },
  { name: 'Nigeria', code: 'NG', dialCode: '+234' },
  { name: 'Norvège', code: 'NO', dialCode: '+47' },
  { name: 'Pologne', code: 'PL', dialCode: '+48' },
  { name: 'Portugal', code: 'PT', dialCode: '+351' },
  { name: 'Russie', code: 'RU', dialCode: '+7' },
  { name: 'Sénégal', code: 'SN', dialCode: '+221' },
  { name: 'Serbie', code: 'RS', dialCode: '+381' },
  { name: 'Singapour', code: 'SG', dialCode: '+65' },
  { name: 'Afrique du Sud', code: 'ZA', dialCode: '+27' },
  { name: 'Corée du Sud', code: 'KR', dialCode: '+82' },
  { name: 'Espagne', code: 'ES', dialCode: '+34' },
  { name: 'Suède', code: 'SE', dialCode: '+46' },
  { name: 'Suisse', code: 'CH', dialCode: '+41' },
  { name: 'Thaïlande', code: 'TH', dialCode: '+66' },
  { name: 'Tunisie', code: 'TN', dialCode: '+216' },
  { name: 'Turquie', code: 'TR', dialCode: '+90' },
  { name: 'Émirats arabes unis', code: 'AE', dialCode: '+971' },
  { name: 'Royaume-Uni', code: 'GB', dialCode: '+44' },
  { name: 'États-Unis', code: 'US', dialCode: '+1' },
];